#!/bin/sh

set -e

# Reload systemd to pick up the new service file
systemctl daemon-reload

# Enable and start the default BTCUSDT collector service
systemctl enable collector@BTCUSDT
systemctl start collector@BTCUSDT
echo "Started collector@BTCUSDT service"

exit 0
